### ISSUE TITLE
Add Play Framework samples

### ISSUE THREAD

**Issue by benmccann** [swagger-api/swagger-samples#35]
Old versions are available at https://github.com/swagger-api/swagger-core/tree/92ead0ffc7b36691134b02de6c217f7f8f93d137/samples

**Comment by webron** [comment]
We currently keep the samples here 2.0 only. Since we don't officially support 2.0 for Play, those will not be added here.

**Comment by benmccann** [comment]
Ok, thanks. I'm trying to update the Play module. I might be able to take a look to see what's required for 2.0. I'm starting to get blocked on working on it though until I get some of my PRs merged - https://github.com/swagger-api/swagger-play/pulls

**Comment by fehguy** [comment]
Hi @benmccann I should be getting to those in just a few...

**Comment by benmccann** [comment]
Awesome. Thanks @fehguy !
