### ISSUE TITLE
[Question] Swagger Sample JAXRS-CXF

### ISSUE THREAD

**Issue by hiveship** [swagger-api/swagger-samples#43]
I have found the sample that use Java JAXRS-CXF. I would like to know how I can generate it ? I have not found any documentation about it :/

**Comment by fehguy** [comment]
What do you mean?  How do you use the code generator to make the jaxrs-cxf version?

**Comment by hiveship** [comment]
Exactly :)

Le lundi 11 janvier 2016, Tony Tam <notifications@github.com> a écrit :

> What do you mean? How do you use the code generator to make the jaxrs-cxf
> version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-samples/issues/43#issuecomment-170634590>
> .
>


-- 

*Maëlig NANTEL*
Mobile : +33 (0)6 69 47 39 00
Mail : *maelig.nantel@gmail.com <maelig.nantel@gmail.com>*

**Comment by webron** [comment]
There's no template for CXF but you can easily create one. The sample was written manually.

**Comment by hiveship** [comment]
Ok :) Is there any documentation about how creating a new template ? I may try to create one for CXF, and in case of success; I will publish it ;)

**Comment by webron** [comment]
Yup - https://github.com/swagger-api/swagger-codegen#making-your-own-codegen-modules

**Comment by hiveship** [comment]
Thank you, I'm working on it. If I success, I'll send a PR.
