### ISSUE TITLE
java-resteasy Error: Uncaught ReferenceError: JSONEditor is not defined

### ISSUE THREAD

**Issue by 4F2E4A2E** [swagger-api/swagger-samples#45]
Hello guys! 

Thank you for this amazing library, we are having fun learning it.
Right now we are having a hard time getting it to run properly, this is what we did:

1. Download the master swagger-samples: https://github.com/swagger-api/swagger-samples/archive/master.zip
1. mvn install
2. cd java/java-resteasy/ && mvn jetty:run
3. Browse over to http://localhost:8002
4. See the error in the debug mode of you browser: Uncaught ReferenceError: JSONEditor is not defined

What are we doing wrong?
Should we wait and go for the release 2.0.0?
Is there a minimalistic example of how to use swagger for already existing resteasy projects?

Thanks in advance.

**Comment by fehguy** [comment]
Please add this line:

```
  <script src='lib/jsoneditor.min.js' type='text/javascript'></script>
```

to your index.html.  I'll make sure the samples are updated with this change.

**Comment by 4F2E4A2E** [comment]
Yes it worked preety good! Thank you.
