### ISSUE TITLE
Add a resteasy.scan = true example

### ISSUE THREAD

**Issue by JathinSanghvi** [swagger-api/swagger-samples#55]
I am unable to configure a simple rest easy project with resteasy.scan = true. with no servelet mapping 
```

<context-param>
		<param-name>resteasy.scan</param-name>
		<param-value>true</param-value>
	</context-param>
```

and one resource
```
@Path("/physician")
public class PhysicianMappingService {
@GET
	@Path("/npi/{param}")
	@Produces(MediaType.APPLICATION_JSON)
	public Response getPhysician(@PathParam("param") String npi, @Context ServletContext servletContext) {
// some impl code
}
```

the max i was able to achieve was getting a high level output with no api info.

{"swagger":"2.0","info":{"version":"1.0.4","title":"Physician Mapping Service"},"basePath":"/http://localhost:8080/PhysicianMappingService"}

Please help me to get a sample app with this configuration

**Comment by webron** [comment]
You'd need to explicitly tell swagger-core which packages to scan. See https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-RESTEasy-2.X-Project-Setup-1.5.
