### ISSUE TITLE
Swagger - UI is not showing the API Docs as expected

### ISSUE THREAD

**Issue by raghunila** [swagger-api/swagger-samples#69]
Hello Swagger team,

I started the project with out any problem.  below link works fine,
http://localhost:8002/api/pet/1
http://localhost:8002/api/swagger.json
but swagger-ui is failing to list our API and its methods.
http://localhost:8002/#, just displays html bar with swagger.io, two text boxes and explore button.

Is something missing.

**Comment by raghunila** [comment]
Some of the JS versions were wrong. Please resolve and push the new code. 
<script src='lib/highlight.9.1.0.pack.js' type='text/javascript'></script>
<script src='lib/handlebars-4.0.5.js' type='text/javascript'></script>

**Comment by fehguy** [comment]
Go update your `index.html` from that in the project.  https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html
