### ISSUE TITLE
MessageBodyWriter not found for media type=application/xml

### ISSUE THREAD

**Issue by franciscocpg** [swagger-api/swagger-samples#8]
Getting
**org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyWriter not found for media type=application/xml, type=class java.util.ArrayList, genericType=class java.util.ArrayList**
when running java-jersey2 with application/xml response.

I tried to add
```
<dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-jaxb</artifactId>
            <version>2.19</version>
        </dependency>
 ```

to pom.xml with no luck.

What am I missing here?

**Comment by webron** [comment]
Is this related to a specific sample?

**Comment by franciscocpg** [comment]
Yes,  it's **java-jersey2** sample

**Comment by franciscocpg** [comment]
Any news?

**Comment by mar612** [comment]
To fix your issue, you need to wrap the list using GenericEntity<T> to preserve the type.
See PR#10

**Comment by franciscocpg** [comment]
Yes, it solved the issue.

**Comment by mar612** [comment]
You're welcome @franciscocpg
