### ISSUE TITLE
swagger ui just parse the reponse code 200

### ISSUE THREAD

**Issue by freeunion1possible** [swagger-api/swagger-samples#85]
i just found that when http response status code not 200, such as 500 or etc, the 3.0.x version can not parse the response body. it work well under 2.2.10.  Is there anybody has solution for this issue. i am not sure whether is a bug.
![image](https://user-images.githubusercontent.com/19768997/27385539-a475f2fc-56c5-11e7-81b6-c67e3e3aa89f.png)

**Comment by webron** [comment]
It's fixed in the latest UI.
