### ISSUE TITLE
BasePath not added to swagger.json in java-resteasy sample

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-samples#9]
_From @Isnogud77 on June 23, 2015 8:21_

I've created a REST Api running on JBoss EAP 6 with RESTEasy which is based on the java-resteasy sample. I noticed in my application that basePath isn't added to the swagger.json even though I've declared that in the Bootstrap class. All other information seem to be added correctly.

I then tried to reproduce the issue by running the sample and it's exactly the same behaviour. The basePath is missing there as well. So, this sample could be used to debug/reproduce the issue. 

This leads to the situation that I can examine the API in the UI but can't execute interactive requests. 

_Copied from original issue: swagger-api/swagger-core#1194_

**Comment by webron** [comment]
Thanks for reporting, @Isnogud77, there's indeed a problem with the sample. The problem arises from a conflict in configuration.

**Comment by Isnogud77** [comment]
@webron I don't see a fix in the sample. Could you please explain what needs to be changed in order to get this working?

**Comment by webron** [comment]
The issue is not closed, so.. you don't see the fix. If you're looking to integrate with RESTEasy, I'd suggest just following the [integration guide](https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-RESTEasy-2.X-Project-Setup-1.5).
